spring.application.name=authentication-system

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/authentication_db
spring.datasource.username=postgres
spring.datasource.password=jane

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=8080