spring.application.name=authentication-system

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/authentication_db
spring.datasource.username=postgres
spring.datasource.password=jane

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Server
server.port=8080

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=janeebaimay@gmail.com
spring.mail.password=lrnzxvasvzsxotpc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

####################################################
# KEYCLOAK CONFIGURATION
####################################################

spring.security.oauth2.client.registration.keycloak.client-id=authentication-system
spring.security.oauth2.client.registration.keycloak.client-secret=FoWMp6gIsJssSVcQ3Fd30B7HASSrxaV2
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8180/realms/AuthenticationSystem

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/AuthenticationSystem